import { useLanguage } from "@/contexts/LanguageContext";
export default function PrivacyPage() {
  const { t } = useLanguage();
  return (
    <div className="min-h-screen bg-[var(--cream-50)]" style={{ paddingTop: "4rem" }}>
      <div className="bg-[var(--forest-900)] py-12 text-white"><div className="container"><h1 className="text-headline text-white">{t({ fr: "Politique de confidentialité", en: "Privacy Policy", be: "Privacy Policy" })}</h1></div></div>
      <div className="container py-16 max-w-3xl prose-eco">
        <p className="text-caption text-[var(--slate-500)] mb-8">{t({ fr: "Dernière mise à jour : juillet 2025", en: "Last updated: July 2025", be: "Last updated: July 2025" })}</p>
        <h2 className="text-subheadline text-[var(--forest-950)] mb-4">{t({ fr: "1. Responsable du traitement", en: "1. Data controller", be: "1. Data controller" })}</h2>
        <p className="text-lead mb-6">{t({ fr: "Sève & Bois Escapes, Laforet, Wallonie, Belgique. Contact : support@sevebois.be", en: "Sève & Bois Escapes, Laforet, Wallonia, Belgium. Contact: support@sevebois.be", be: "Sève & Bois Escapes, Laforet, Wallonia, Belgium. Contact: support@sevebois.be" })}</p>
        <h2 className="text-subheadline text-[var(--forest-950)] mb-4">{t({ fr: "2. Données collectées", en: "2. Data collected", be: "2. Data collected" })}</h2>
        <p className="text-lead mb-6">{t({ fr: "Nous collectons les données que vous nous fournissez lors d'une réservation ou d'une prise de contact : nom, email, téléphone, dates de séjour, nombre de personnes. Nous collectons également des données de navigation anonymisées via des cookies analytiques (avec votre consentement).", en: "We collect the data you provide when making a booking or contact: name, email, phone, stay dates, number of guests. We also collect anonymised browsing data via analytical cookies (with your consent).", be: "We collect the data you provide when making a booking or contact: name, email, phone, stay dates, number of guests. We also collect anonymised browsing data via analytical cookies (with your consent)." })}</p>
        <h2 className="text-subheadline text-[var(--forest-950)] mb-4">{t({ fr: "3. Finalités du traitement", en: "3. Purposes of processing", be: "3. Purposes of processing" })}</h2>
        <p className="text-lead mb-6">{t({ fr: "Vos données sont utilisées pour : traiter votre réservation, vous envoyer une confirmation, vous contacter en cas de besoin, améliorer notre service. Nous ne vendons jamais vos données à des tiers.", en: "Your data is used to: process your booking, send you a confirmation, contact you if needed, improve our service. We never sell your data to third parties.", be: "Your data is used to: process your booking, send you a confirmation, contact you if needed, improve our service. We never sell your data to third parties." })}</p>
        <h2 className="text-subheadline text-[var(--forest-950)] mb-4">{t({ fr: "4. Vos droits (RGPD)", en: "4. Your rights (GDPR)", be: "4. Your rights (GDPR)" })}</h2>
        <p className="text-lead mb-6">{t({ fr: "Conformément au RGPD, vous disposez d'un droit d'accès, de rectification, d'effacement, de portabilité et d'opposition. Pour exercer ces droits, contactez-nous à support@sevebois.be.", en: "In accordance with GDPR, you have the right to access, rectification, erasure, portability and objection. To exercise these rights, contact us at support@sevebois.be.", be: "In accordance with GDPR, you have the right to access, rectification, erasure, portability and objection. To exercise these rights, contact us at support@sevebois.be." })}</p>
        <h2 className="text-subheadline text-[var(--forest-950)] mb-4">{t({ fr: "5. Conservation des données", en: "5. Data retention", be: "5. Data retention" })}</h2>
        <p className="text-lead mb-6">{t({ fr: "Les données de réservation sont conservées 5 ans à des fins comptables. Les données de newsletter sont conservées jusqu'à désinscription.", en: "Booking data is retained for 5 years for accounting purposes. Newsletter data is retained until unsubscription.", be: "Booking data is retained for 5 years for accounting purposes. Newsletter data is retained until unsubscription." })}</p>
        <h2 className="text-subheadline text-[var(--forest-950)] mb-4">{t({ fr: "6. Cookies", en: "6. Cookies", be: "6. Cookies" })}</h2>
        <p className="text-lead">{t({ fr: "Nous utilisons des cookies essentiels (fonctionnement du site) et analytiques (avec consentement). Voir notre politique de cookies pour plus de détails.", en: "We use essential cookies (site functionality) and analytical cookies (with consent). See our cookie policy for more details.", be: "We use essential cookies (site functionality) and analytical cookies (with consent). See our cookie policy for more details." })}</p>
      </div>
    </div>
  );
}
